Document: foldingatomata
Title: Debian foldingatomata Manual
Author: <insert document author here>
Abstract: This manual describes what foldingatomata is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/foldingatomata/foldingatomata.sgml.gz

Format: postscript
Files: /usr/share/doc/foldingatomata/foldingatomata.ps.gz

Format: text
Files: /usr/share/doc/foldingatomata/foldingatomata.text.gz

Format: HTML
Index: /usr/share/doc/foldingatomata/html/index.html
Files: /usr/share/doc/foldingatomata/html/*.html
